name: LoveOrtho
favicon: null
layout_spectrum: 1
typography_spectrum: 0.81064
title: 'A website centered around "Slow Orthodontics" - Slow cooking will lead to beautifully finished cases :)'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#1da3bc'
    - '#9ae7f5'
    - '#012c34'
    - '#036f83'
    - '#628d95'
  brandStrength: 0.125
  lightness: 0.1875
  saturation: 0.5
  rhythmicContrast: 0.75
purpose: []
